BlogMVC/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace BlogMVC.Models
{
    public class Blog
    {
        public int ID { get; set; }
        public string title { get; set; }
        [DataType(DataType.MultilineText)]
        public string shortDetail { get; set; }
        [DataType(DataType.MultilineText)]
        public string detail { get; set; }
        public string thumb { get; set; }
        public bool status { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime datePublic { get; set; }
        public int CategoryId { get; set; }
        public virtual Category category { get; set; }

        public virtual ICollection<Position> Positions { get; set; }
    }
    public class BlogDBContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        public DbSet<Category> Categories { get; set; }
        public DbSet<Position> Positions { get; set; }
    }
    

}

BlogMVC/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogMVC.Models
{
    public class Category
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public virtual ICollection<Blog> Blogs { get; set; }

    }
}

BlogMVC/Models/Position.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogMVC.Models
{
    public class Position
    {
        public int ID { get; set; }
        public string address { get; set; }
        public int BlogId { get; set; }
        public virtual Blog blog { get; set; }
    }
}

BlogMVC/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogMVC.Models;

namespace BlogMVC.Controllers
{
    public class BlogsController : Controller
    {
        private BlogDBContext db = new BlogDBContext();
        List<string> listpos = new List<string>{"Việt Nam","Châu Á","Châu Âu","Châu Mỹ"};

        // GET: Blogs
        public ActionResult Index()
        {
            return View(db.Blogs.ToList());
        }

        // GET: Blogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: Blogs/Create
        public ActionResult Create()
        {
            var list = new SelectList(db.Categories.ToList(), "ID", "Title");
            ViewData["listCategories"] = list;
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,title,shortDetail,detail,thumb,status,datePublic,CategoryId")] Blog blog)
        {
            
            if (ModelState.IsValid)
            {
                
                db.Blogs.Add(blog);
                db.SaveChanges();
                for (int i = 1; i <= 4; i++)
                {
                    string checkbox = "checkbox" + i;
                    if (Request.Form[checkbox] != null)
                    {
                        Position position = new Position();
                        position.BlogId = blog.ID;
                        position.address = Request.Form[checkbox];
                        position.ID = 0;
                        db.Positions.Add(position);
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            var list = new SelectList(db.Categories.ToList(), "ID", "Title");
            ViewData["listCategories"] = list;
            for (int i= 0;i < 4;i++)
            {
                string checkbox = "checkbox" + (i+1);
                if(blog.Positions.Where(m => m.address == listpos[i]).Count()>0)
                    ViewData[checkbox] = "checked";
                else
                {
                    ViewData[checkbox] = "";
                }
            }
            
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,title,shortDetail,detail,thumb,status,datePublic,CategoryId")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                db.Positions.RemoveRange(db.Positions.ToList().FindAll(m => m.BlogId == blog.ID).ToList());
                for (int i = 1; i <= 4; i++)
                {
                    string checkbox = "checkbox" + i;
                    if (Request.Form[checkbox] != null)
                    {
                        Position position = new Position();
                        position.BlogId = blog.ID;
                        position.address = Request.Form[checkbox];
                        position.ID = 0;
                        db.Positions.Add(position);
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            db.Blogs.Remove(blog);
            db.Positions.RemoveRange(db.Positions.ToList().FindAll(m => m.BlogId == blog.ID).ToList());
            if (blog == null)
            {
                return HttpNotFound();
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.Blogs.Find(id);
            db.Blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Searching (FormCollection fc, string title) {
            var blogsearching = from m in db.Blogs where m.title==title select m ;
            if (!String.IsNullOrEmpty(title))
            {
                blogsearching = db.Blogs.Where(m => m.title == title);
            }
            return View(blogsearching);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlogMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BlogMVC/Views/Blogs/Create.cshtml
@model BlogMVC.Models.Blog



@{
    ViewBag.Title = "Create";
}
<div class="border-layout">
    <div class="header-title">
        <h2>Create</h2>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
@*            <h4>Blog</h4>*@
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.shortDetail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.shortDetail, new { htmlAttributes = new { @class = "form-control w-100", rows = "3" } })
                    @Html.ValidationMessageFor(model => model.shortDetail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.detail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.detail, new { htmlAttributes = new { @class = "form-control w-100", rows = "10" } })
                    @Html.ValidationMessageFor(model => model.detail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.thumb, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.thumb, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.thumb, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.status) yes
                        @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.datePublic, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.datePublic, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.datePublic, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>)ViewData["listCategories"])
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Positions, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="checkbox" class="checkbox-inline" value="Việt Nam" name="checkbox1" />Việt Nam
                    <input type="checkbox" class="checkbox-inline" value="Châu Á" name="checkbox2" />Châu Á
                    <input type="checkbox" class="checkbox-inline" value="Châu Âu" name="checkbox3" />Châu Âu
                    <input type="checkbox" class="checkbox-inline" value="Châu Mỹ" name="checkbox4" />Châu Mỹ
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlogMVC/Views/Blogs/Delete.cshtml
@model BlogMVC.Models.Blog

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Blog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.shortDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.shortDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.thumb)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.thumb)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datePublic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datePublic)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BlogMVC/Views/Blogs/Details.cshtml
@model BlogMVC.Models.Blog

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Blog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.shortDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.shortDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.thumb)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.thumb)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datePublic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datePublic)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BlogMVC/Views/Blogs/Edit.cshtml
@model BlogMVC.Models.Blog

@{
    ViewBag.Title = "Edit";
}


<div class="border-layout ">
    <div class="header-title">
        <h2>Edit</h2>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
@*            <h4>Blog</h4>*@
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.shortDetail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.shortDetail, new { htmlAttributes = new { @class = "form-control w-100", rows = "3" } })
                    @Html.ValidationMessageFor(model => model.shortDetail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.detail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.detail, new { htmlAttributes = new { @class = "form-control w-100", rows = "5" } })
                    @Html.ValidationMessageFor(model => model.detail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.thumb, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.thumb, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.thumb, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.status) yes
                        @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.datePublic, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.datePublic, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                    @Html.ValidationMessageFor(model => model.datePublic, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>)ViewData["listCategories"])
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Positions, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    <input type="checkbox" class="checkbox-inline" value="Việt Nam" name="checkbox1" @ViewData["checkbox1"].ToString() /> Việt Nam
                    <input type="checkbox" class="checkbox-inline" value="Châu Á" name="checkbox2" @ViewData["checkbox2"].ToString() />Châu Á
                    <input type="checkbox" class="checkbox-inline" value="Châu Âu" name="checkbox3" @ViewData["checkbox3"].ToString() />Châu Âu
                    <input type="checkbox" class="checkbox-inline" value="Châu Mỹ" name="checkbox4" @ViewData["checkbox4"].ToString() />Châu Mỹ
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlogMVC/Views/Blogs/Index.cshtml
@model IEnumerable<BlogMVC.Models.Blog>

@{
    ViewBag.Title = "Index";
    var address = "";
}
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
<div class="border-layout ">
    <div class="header-title">
        <h2>Index</h2>
    </div>
    <div class="">
        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.shortDetail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.detail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.thumb)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.datePublic)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.category.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Positions)
                </th>
                <th>
                    Edit
                </th>
                <th>
                    Detail
                </th>
                <th>
                    Delete
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.shortDetail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.detail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.thumb)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.datePublic)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.category.Title)
                    </td>
                    <td>
                        @foreach (var position in item.Positions)
                        {
                            if (position.BlogId == item.ID)
                            {
                                address += position.address + " ";
                            }
                        }
                        @Html.DisplayFor(modelItem => address)
                        @{
                            address = "";
                        }
                    </td>
                    <td>
                        <button class="btn btn-primary  ">
                            @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "color-text-white" })
                        </button>
                    </td>
                    <td>
                        <button class="btn btn-primary ">
                            @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "color-text-white" })
                        </button>
                    </td>
                    <td>
                        <button class="btn btn-danger">
                            @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "color-text-white" })
                        </button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

BlogMVC/Views/Blogs/Searching.cshtml
@model IEnumerable<BlogMVC.Models.Blog>

@{
    ViewBag.Title = "Searching";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var address = "";
}


<div>
    <h2>Searching</h2>
    <div>
        @using (Html.BeginForm())
        {
            <p>
                Title: @Html.TextBox("title","")
                <input type="submit" value="Filter" />
            </p>
        }
    </div>
    <div class="">
        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.shortDetail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.detail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.thumb)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.datePublic)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.category.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Positions)
                </th>
                <th>
                    Edit
                </th>
                <th>
                    Detail
                </th>
                <th>
                    Delete
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.shortDetail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.detail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.thumb)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.datePublic)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.category.Title)
                    </td>
                    <td>
                        @foreach (var position in item.Positions)
                        {
                            if (position.BlogId == item.ID)
                            {
                                address += position.address + " ";
                            }
                        }
                        @Html.DisplayFor(modelItem => address)
                        @{
                            address = "";
                        }
                    </td>
                    <td>
                        <button class="btn btn-primary  ">
                            @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "color-text-white" })
                        </button>
                    </td>
                    <td>
                        <button class="btn btn-primary ">
                            @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "color-text-white" })
                        </button>
                    </td>
                    <td>
                        <button class="btn btn-danger">
                            @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "color-text-white" })
                        </button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

BlogMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BlogMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BlogMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

BlogMVC/Views/Shared/_Footer.cshtml
<div class='footer w-100'>
    Copyright 2021
    <a>devfast</a>
</div>

BlogMVC/Views/Shared/_Menu.cshtml
<div class='col-2 menu-position '>
    <div class=''>
        <ul class='p-0 flex-column'>
            <li class="box-list">
                     @Html.ActionLink("List", "Index", "Blogs")
            </li>
            <li class="box-list">
                     @Html.ActionLink("Edit", "Create", "Blogs")
            </li>
            <li class="box-list">
                    @Html.ActionLink("Search", "Searching", "Blogs")
            </li>
        </ul>
    </div>
</div>